defaults:
- _self_
- task: halfcheetah-medium-replay-v2
pipeline_name: dd_d4rl
device_id: 0
mode: diffusion_training # diffusion_training -> invdyn_training (optional) -> inference
seed: 0
invdyn_hidden_dim: 512

# Training
diffusion_training_steps: 1000000
invdyn_training_steps: 200000
save_interval: 200000
# Inference
diffusion_ckpt: 1000000
invdyn_ckpt: 200000
solver: ddpm
invdyn_from_pretrain: False
sampling_steps: 10
num_envs: 50
num_episodes: 1

# hydra
hydra:
  job:
    chdir: false