defaults:
  - _self_
  - task: halfcheetah-medium-v2

pipeline_name: idql_d4rl
device_id: 1
mode: inference  # bc_training -> iql_training (optional) -> inference
seed: 0

# Environment
normalize_reward: True

# Training
bc_training_steps: 1000000
iql_training_steps: 1000000
save_interval: 100000

# Inference
bc_ckpt: 1000000
iql_ckpt: 1000000
solver: ddpm
iql_from_pretrain: False
sampling_steps: 5
num_envs: 50
num_episodes: 3
num_candidates: 256

# hydra
hydra:
  job:
    chdir: false
