defaults:
  - _self_
  - task: antmaze-large-play-v2

pipeline_name: diffuser_d4rl
device_id: 0
mode: inference  # training -> inference
seed: 0

# Training
diffusion_training_steps: 1000000
classifier_training_steps: 1000000
save_interval: 100000

# Inference
ckpt: 1000000
solver: ddpm
sampling_steps: 5
num_envs: 50
num_episodes: 3
num_candidates: 64

# hydra
hydra:
  job:
    chdir: false
