defaults:
- _self_
- task: halfcheetah-medium-expert-v2
pipeline_name: edp_d4rl
mode: training
seed: 0
device_id: 1
# Actor
solver: ddpm
sampling_steps: 15
# Training
training_steps: 2000000
ema_update_interval: 5
log_interval: 1000
save_interval: 1000000
# Inference
ckpt: 2000000
num_envs: 50
num_episodes: 1
num_candidates: 50
temperature: 0.5
use_ema: True
# hydra
hydra:
  job:
    chdir: false