defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: adaptdiffuser_d4rl
device_id: 0
mode: inference  # training -> finetune -> inference
seed: 0

# Training
diffusion_gradient_steps: 1000000
classifier_gradient_steps: 1000000
save_interval: 100000

# Finetune
diffusion_ckpt: 1000000

# Inference
ckpt: 200_000
solver: ddpm
sampling_steps: 5
num_envs: 50
num_episodes: 1
num_candidates: 64

# hydra
hydra:
  job:
    chdir: false
